name: Deploy via FTP

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # - name: Setup Node 20
      #   uses: actions/setup-node@v4
      #   with:
      #     node-version: 20.20.0
      #
      # - name: Install dependencies
      #   run: npm install
      #
      # - name: Update packages
      #   run: npm update
      #
      # - name: Build project
      #   run: npm run build

      - name: Sync files (FTP)
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: domains/laravel.andersonls.com.br/public_html/
          protocol: ftp
          port: 21
